### ISSUE TITLE
readline does not wrap

### ISSUE THREAD

**Issue by Ocawesome101** [Ryan-Te/PhileOS-OC#2]
This may be a feature you intend to implement later.  Your `term.read` implementation does not wrap, which means that entering long commands is difficult on smaller (i.e. 50x16) terminals.

This appears to be due to its using `gpu.set`.

You define a `term.print` function, so why not use it?  You may need to move cursor management to not be exclusively a feature of the `.read()` function.

[ULOS's `readline()`](https://github.com/ocawesome101/ulos-external/blob/master/corelibs/lib/readline.lua) is a good example of my preferred method for redrawing - note that you'll have to modify it somewhat to work without a VT100 emulator but it should still be relatively simple.

Here's some pseudocode:
```
dist_from_end = 0
buffer = ""
loop:
  check input
  if input is a key, add input to buffer at (#buffer - dist_from_end)
  if input is backspace, delete character from buffer at (#buffer - dist_from_end)
  redraw:
    if dist_from_end == 0:  only draw the character that was added;
    otherwise:  draw buffer[#buffer - dist_from_end] to buffer[#buffer], then move the cursor back dist_from_end characters
```

**Comment by Ryan-Te** [comment]
fixed!
